services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'         # host 5433 → container 5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: 
